name: Deploy to Production

on:
  pull_request_target:
    types: [closed]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BACKEND: ghcr.io/${{ github.repository }}/backend
  IMAGE_NAME_WORKER: ghcr.io/${{ github.repository }}/worker
  IMAGE_NAME_FRONTEND: ghcr.io/${{ github.repository }}/frontend

jobs:
  build:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    outputs:
      date_stamp: ${{ steps.date.outputs.date_stamp }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Set Docker tag
        id: date
        run: echo "date_stamp=$(date +%s)" >> "$GITHUB_OUTPUT"

      - name: Build Backend image
        run: |
          docker build -t ${{ env.IMAGE_NAME_BACKEND }}:${{ steps.date.outputs.date_stamp }} -t ${{ env.IMAGE_NAME_BACKEND }}:latest -f docker/Dockerfile.backend .

      - name: Build Worker image
        run: |
          docker build -t ${{ env.IMAGE_NAME_WORKER }}:${{ steps.date.outputs.date_stamp }} -t ${{ env.IMAGE_NAME_WORKER }}:latest -f docker/Dockerfile.worker ./worker

      - name: Build Frontend image
        run: |
          docker build -t ${{ env.IMAGE_NAME_FRONTEND }}:${{ steps.date.outputs.date_stamp }} -t ${{ env.IMAGE_NAME_FRONTEND }}:latest -f docker/Dockerfile.frontend ./frontend

      - name: Save Docker images
        run: |
          docker save ${{ env.IMAGE_NAME_BACKEND }}:${{ steps.date.outputs.date_stamp }} -o backend.tar
          docker save ${{ env.IMAGE_NAME_WORKER }}:${{ steps.date.outputs.date_stamp }} -o worker.tar
          docker save ${{ env.IMAGE_NAME_FRONTEND }}:${{ steps.date.outputs.date_stamp }} -o frontend.tar

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            backend.tar
            worker.tar
            frontend.tar

  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docker-images

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GB_TOKEN }}

      - name: Load and push Backend image
        run: |
          docker load -i backend.tar
          docker tag ${{ env.IMAGE_NAME_BACKEND }}:${{ needs.build.outputs.date_stamp }} ${{ env.IMAGE_NAME_BACKEND }}:latest
          docker push ${{ env.IMAGE_NAME_BACKEND }}:${{ needs.build.outputs.date_stamp }}
          docker push ${{ env.IMAGE_NAME_BACKEND }}:latest

      - name: Load and push Worker image
        run: |
          docker load -i worker.tar
          docker tag ${{ env.IMAGE_NAME_WORKER }}:${{ needs.build.outputs.date_stamp }} ${{ env.IMAGE_NAME_WORKER }}:latest
          docker push ${{ env.IMAGE_NAME_WORKER }}:${{ needs.build.outputs.date_stamp }}
          docker push ${{ env.IMAGE_NAME_WORKER }}:latest

      - name: Load and push Frontend image
        run: |
          docker load -i frontend.tar
          docker tag ${{ env.IMAGE_NAME_FRONTEND }}:${{ needs.build.outputs.date_stamp }} ${{ env.IMAGE_NAME_FRONTEND }}:latest
          docker push ${{ env.IMAGE_NAME_FRONTEND }}:${{ needs.build.outputs.date_stamp }}
          docker push ${{ env.IMAGE_NAME_FRONTEND }}:latest

  deploy:
    needs: push
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd v-insight
            docker compose down
            docker compose pull
            docker compose up -d