name: Build and push SSL Checker docker

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/ssl-checker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GB_TOKEN }}

      - name: Set Docker tag
        id: date
        run: echo "DATE_STAMP=$(date +%s)" >> "$GITHUB_ENV"

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:build_at-${{ env.DATE_STAMP }} -t ${{ env.IMAGE_NAME }}:latest -f ssl-checker/Dockerfile ssl-checker

      - name: Push Docker images
        run: |
          docker push ${{ env.IMAGE_NAME }}:build_at-${{ env.DATE_STAMP }}
          docker push ${{ env.IMAGE_NAME }}:latest